-- Real-time task notifications, generated by the database.
--
-- THE HOLE THIS CLOSES
-- `useAppStore.notifications` was an in-memory array and the two task
-- producers were pointed at the wrong person. Both sat inside updateTask /
-- createTask and read `currentUserProfile` — the ACTOR — then asked "is the
-- new assignee me?":
--
--   const nowMine = updates.assigned_to_id === me.id
--   if (nowMine && !wasMine) addNotification(...)
--
-- That runs in the assigner's browser. Assign a task to someone else and
-- `nowMine` is false, so nothing is emitted anywhere — the recipient is never
-- told. The only case that ever fired was assigning a task to yourself, which
-- is the one notification nobody needs. Mentions had the same shape. And
-- because the array was local, even a correct notification died on reload and
-- could never reach another device.
--
-- WHAT THIS DOES
--   1. Creates `public.notifications` — one row per (recipient, event). RLS
--      scopes every row to its recipient, which also makes the realtime
--      subscription self-filtering: postgres_changes evaluates RLS per
--      subscriber, so a client only ever receives its own rows.
--   2. Adds an AFTER INSERT OR UPDATE trigger on `tasks` that writes those
--      rows for assignment and @mention events. The producer belongs below the
--      client for the same reason task attribution does (see
--      tasks_mandatory_attribution.sql): a notification that only exists when
--      one particular browser tab happens to run the right branch is not a
--      guarantee. This fires for writes from any client, the SQL editor, the
--      seed script, or a future service worker.
--   3. Publishes the table on `supabase_realtime`. This is load-bearing and
--      easy to miss — realtime.subscription filters on pg_publication_tables,
--      so a table absent from the publication does NOT error the channel, it
--      just silently never delivers. See realtime_publish_profiles.sql, which
--      fixed exactly this for `profiles`.
--
-- WHAT THIS DELIBERATELY DOES NOT DO
-- No notification when you act on yourself. The trigger compares the resolved
-- recipient against `auth.uid()` and skips the match, so self-assigning and
-- @mentioning yourself stay silent. Writes with no JWT (seed script, service
-- role, SQL editor) have a null auth.uid() and therefore never match, so
-- seeded rows still notify — which is what makes the seed demoable.
--
-- Mentions resolve by NAME, case-insensitively, because that is what the app
-- stores: `tasks.mentions` is a text[] of display names scraped from comment
-- text by a regex, e.g. {'fold demo','Ketan patni'}. `profiles` holds more
-- than one row per human (one per email they ever signed up with — three rows
-- are named "Alok Kumar"), so a name can resolve to several recipients. All of
-- them get a row: a person only signs in as one of those identities, so they
-- see exactly one notification.

begin;

-- ── 1. Table ────────────────────────────────────────────────────────────────
create table if not exists public.notifications (
  id           uuid primary key default gen_random_uuid(),
  -- Deliberately NOT a foreign key. The trigger below inserts inside the
  -- task write's own transaction, so an FK violation here would roll back
  -- the user's task edit — a notification must never be able to break a
  -- save. Recipients come from `profiles.id` / `tasks.assigned_to_id`, and a
  -- value that no longer resolves just yields a row nobody can read (RLS
  -- matches on auth.uid()), which is a strictly better failure than a
  -- rejected update.
  recipient_id uuid        not null,
  actor_id     uuid,
  actor_name   text,
  type         text        not null,
  title        text        not null,
  body         text,
  action       text,
  -- tasks.id is a bigint identity column, not a uuid.
  task_id      bigint      references public.tasks(id) on delete cascade,
  read         boolean     not null default false,
  created_at   timestamptz not null default now()
);

-- The only read pattern: "my newest 50".
create index if not exists notifications_recipient_created_idx
  on public.notifications (recipient_id, created_at desc);

-- Unread badge count — partial index keeps it tiny as history grows.
create index if not exists notifications_unread_idx
  on public.notifications (recipient_id)
  where not read;

-- ── 2. RLS ──────────────────────────────────────────────────────────────────
-- Recipient-scoped in both directions. This is also what makes the realtime
-- channel safe to subscribe to without a client-side filter.
alter table public.notifications enable row level security;

drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own
  on public.notifications for select
  to authenticated
  using (recipient_id = auth.uid());

-- Mark-as-read / mark-all-read. Recipient may only touch their own rows, and
-- the WITH CHECK stops a row being re-addressed to someone else.
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own
  on public.notifications for update
  to authenticated
  using (recipient_id = auth.uid())
  with check (recipient_id = auth.uid());

drop policy if exists notifications_delete_own on public.notifications;
create policy notifications_delete_own
  on public.notifications for delete
  to authenticated
  using (recipient_id = auth.uid());

-- No INSERT policy on purpose: rows are only ever created by the trigger
-- below, which is SECURITY DEFINER and therefore bypasses RLS. A client
-- cannot manufacture a notification for another user.

-- ── 3. Producer trigger ─────────────────────────────────────────────────────
create or replace function public.emit_task_notifications()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor            uuid := auth.uid();
  actor_label      text;
  assignee_changed boolean;
  new_mentions     text[];
  mention          text;
begin
  -- Display name for the actor, best-effort. Falls back to the row's own
  -- attribution so a seeded or service-role write still reads sensibly.
  select coalesce(p.full_name, p.email, new.created_by, 'Someone')
    into actor_label
    from public.profiles p
   where p.id = actor;
  actor_label := coalesce(actor_label, new.created_by, 'Someone');

  -- ── Assignment ──
  -- INSERT: created already pointing at someone. UPDATE: assignee changed.
  -- `is distinct from` handles the null transitions that `<>` would swallow.
  --
  -- The tg_op test is a separate statement on purpose. PL/pgSQL leaves OLD
  -- *unassigned* (not null) in an INSERT trigger, and touching a field on an
  -- unassigned record raises `record "old" is not assigned yet` — so folding
  -- this into one OR'd condition would abort every task INSERT.
  if tg_op = 'INSERT' then
    assignee_changed := new.assigned_to_id is not null;
  else
    assignee_changed := new.assigned_to_id is not null
                    and new.assigned_to_id is distinct from old.assigned_to_id;
  end if;

  if assignee_changed and new.assigned_to_id is distinct from actor then
    insert into public.notifications
      (recipient_id, actor_id, actor_name, type, title, body, action, task_id)
    values
      (new.assigned_to_id, actor, actor_label, 'task.assigned',
       'You were assigned a task', new.name, 'openTask', new.id);
  end if;

  -- ── @mentions ──
  -- Only names added by THIS statement, so editing an unrelated field on a
  -- task that already carries mentions does not re-notify everyone.
  if new.mentions is not null and array_length(new.mentions, 1) > 0 then
    if tg_op = 'INSERT' then
      new_mentions := new.mentions;
    else
      select array(
        select m from unnest(new.mentions) m
        except
        select o from unnest(coalesce(old.mentions, '{}'::text[])) o
      ) into new_mentions;
    end if;

    foreach mention in array coalesce(new_mentions, '{}'::text[]) loop
      insert into public.notifications
        (recipient_id, actor_id, actor_name, type, title, body, action, task_id)
      select p.id, actor, actor_label, 'task.mentioned',
             'You were mentioned in a task', new.name, 'openTask', new.id
        from public.profiles p
       where lower(btrim(p.full_name)) = lower(btrim(mention))
         and p.id is distinct from actor;
    end loop;
  end if;

  return new;
end;
$$;

-- Same lockdown as the other definer functions in this project: the trigger
-- is the only intended caller, so no role gets EXECUTE.
revoke all on function public.emit_task_notifications() from public, anon, authenticated;

drop trigger if exists tasks_emit_notifications on public.tasks;
create trigger tasks_emit_notifications
  after insert or update on public.tasks
  for each row execute function public.emit_task_notifications();

-- ── 4. Realtime ─────────────────────────────────────────────────────────────
-- Without this the client's postgres_changes binding matches nothing and never
-- errors — the failure mode is a channel that looks subscribed and delivers
-- silence. Guarded so re-running the migration is safe.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;

commit;

-- ── Verify ──────────────────────────────────────────────────────────────────
-- Table is published for realtime (this is the one people forget):
--   select tablename from pg_publication_tables
--    where pubname='supabase_realtime' and schemaname='public';
--   Expect `notifications` in the list, alongside direct_messages + profiles.
--
-- Trigger attached:
--   select tgname from pg_trigger
--    where tgrelid='public.tasks'::regclass and not tgisinternal;
--   Expect: tasks_emit_notifications (plus tasks_stamp_created_audit).
--
-- Assignment fires. From the SQL editor (auth.uid() is null there, so nothing
-- is treated as a self-action):
--   update tasks set assigned_to_id = '<a profiles.id>' where id = <task id>;
--   select type, title, body, recipient_id from notifications
--    order by created_at desc limit 1;
--   Expect one row, type='task.assigned'.
--
-- Mention fires, case-insensitively, and only for the newly added name:
--   update tasks set mentions = array['Fold Demo'] where id = <task id>;
--   -- second update adds one name; only the NEW one should notify
--   update tasks set mentions = array['Fold Demo','Ketan patni'] where id = <task id>;
--   select type, body from notifications where type='task.mentioned'
--    order by created_at desc limit 2;
--   Expect exactly one new row from the second update (Ketan), not two.
--
-- No self-notification. Signed in as the assignee in the app, assign a task to
-- yourself; no row should appear:
--   select count(*) from notifications
--    where recipient_id = auth.uid() and task_id = <that task> ;
--   Expect: 0.
--
-- RLS isolation — as an authenticated user, this must only ever return your own:
--   select distinct recipient_id from notifications;
--   Expect: exactly one row, your own auth.uid().
--
-- ── Rollback ────────────────────────────────────────────────────────────────
--   alter publication supabase_realtime drop table public.notifications;
--   drop trigger if exists tasks_emit_notifications on public.tasks;
--   drop function if exists public.emit_task_notifications();
--   drop table if exists public.notifications;
